exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('bars').del()
    .then(function () {
      // Inserts seed entries
      return knex('bars').insert([
        {location: 'rainey', name: 'Container Bar', address: '90 Rainey St'},
        {location: 'rainey', name: 'Icenhauer’s', address: '83 Rainey St'},
        {location: 'rainey', name: 'Clive Bar', address: '609 Davis St'},
        {location: 'rainey', name: 'Half Step', address: '609 Davis St'},
        {location: 'rainey', name: 'Bar 96', address: '96 Rainey St'},
        {location: 'rainey', name: 'Unbarlievable', address: '76 Rainey St'},
        {location: 'rainey', name: 'Parlor Room', address: '88 Rainey St'},
        {location: 'rainey', name: 'Lucille', address: '77 Rainey St'},
        {location: 'rainey', name: 'Bungalow', address: '92 Rainey St'},
        {location: 'rainey', name: 'Lustre Pearl Rainey', address: '94 Rainey St'},
        {location: 'rainey', name: 'Javelina', address: '69 Rainey St'},
        {location: 'rainey', name: 'Bangers', address: '79 Rainey St'},
        {location: 'rainey', name: 'The Alibi', address: '96 Rainey St'},
        {location: 'rainey', name: 'Craft Pride', address: '61 Rainey St'},
        {location: 'rainey', name: 'The Drafting Room', address: '88 1/2 Rainey St'},
        {location: 'rainey', name: 'Geraldine’s', address: '605 Davis St'},
        {location: 'rainey', name: 'Bar Ilegal', address: '609 Davis St'},
        {location: 'rainey', name: 'L’estelle House', address: '88 1/2 Rainey St'},
        {location: 'rainey', name: 'El Naranjo', address: '85 Rainey St'},
        {location: 'rainey', name: 'Emmer & Rye', address: '51 Rainey St'},
        {location: 'dirty', name: 'Library Bar', address: '407 E 6th St'},
        {location: 'dirty', name: 'Blind Pig Pub', address: '317 E 6th St'},
        {location: 'dirty', name: 'Friends Bar', address: '208 E 6th St'},
        {location: 'dirty', name: 'Dirty Dog Bar', address: '505 E 6th St'},
        {location: 'dirty', name: 'Darwin’s Piano Bar', address: '223 E 6th St'},
        {location: 'dirty', name: 'Big Bang Bar', address: '415 E 6th St'},
        {location: 'dirty', name: 'Midnight Cowboy', address: '313 E 6th St'},
        {location: 'dirty', name: 'Moose Knuckle Pub', address: '406 E 6th St'},
        {location: 'dirty', name: 'Coyote Ugly', address: '501 E 6th St'},
        {location: 'dirty', name: 'Bat Bar', address: '218 E 6th St'},
        {location: 'dirty', name: 'Parkside', address: '301 E 6th St'},
        {location: 'dirty', name: 'The Lodge', address: '411 E 6th St'},
        {location: 'dirty', name: 'Peckerheads', address: '402 E 6th St'},
        {location: 'dirty', name: 'Lit Lounge', address: '215 E 6th St'},
        {location: 'dirty', name: 'San Jac Saloon', address: '300 E 6th St'},
        {location: 'dirty', name: '512 Bar', address: '408 E 6th St'},
        {location: 'dirty', name: 'The Jackalope', address: '404 E 6th St'},
        {location: 'dirty', name: 'Thirsty Nickel', address: '325 E 6th St'},
        {location: 'dirty', name: 'Two Bucks', address: '503 E 6th St'},
        {location: 'dirty', name: 'Easy Tiger', address: '709 E 6th St'},
        {location: 'dirty', name: 'Buckshot', address: '422 E 6th St'},
        {location: 'dirty', name: 'Voodoo Room', address: '419 E 6th St'},
        {location: 'dirty', name: 'Pour Choices', address: '401 E 6th St'},
        {location: 'dirty', name: 'Touche', address: '417 E 6th St'},
        {location: 'dirty', name: 'The Dizzy Rooster', address: '306 E 6th St'},
        {location: 'dirty', name: 'Eureka!', address: '200 E 6th St'},
        {location: 'dirty', name: 'Roppolo’s', address: '414 E 6th St'},
        {location: 'dirty', name: 'HandleBar', address: '121 E 5th St'},
        {location: 'dirty', name: 'The Side Bar', address: '602 E 7th St'},
        {location: 'west', name: 'Key Bar', address: '617 W 6th St'},
        {location: 'west', name: 'Star Bar', address: '600 W 6th St'},
        {location: 'west', name: 'The Dogwood', address: '715 W 6th St'},
        {location: 'west', name: 'Parlor and Yard', address: '601 W 6th St'},
        {location: 'west', name: 'The Rustic Tap', address: '613 W 6th St'},
        {location: 'west', name: 'Kung Fu Saloon', address: '716 W 6th St'},
        {location: 'west', name: 'Green Light Social', address: '720 W 6th St'},
        {location: 'west', name: 'Buford’s', address: '700 W 6th St'},
        {location: 'west', name: 'Concrete Cowboy', address: '719 W 6th St'},
        {location: 'west', name: 'Pop', address: '620 W 6th St'},
        {location: 'west', name: 'The Belmont', address: '305 W 6th St'},
        {location: 'west', name: 'Austin Ale House', address: '301 W 6th St'},
        {location: 'west', name: 'Brew Exchange', address: '706 W 6th St'},
        {location: 'west', name: 'The Ranch', address: '710 W 6th St'},
        {location: 'east', name: 'Whistler’s', address: '1816 E 6th St'},
        {location: 'east', name: 'Shangri-La', address: '1016 E 6th St'},
        {location: 'east', name: 'Revelry Kitchen + Bar', address: '1410 E 6th St'},
        {location: 'east', name: 'Violent Crown Social Club', address: '1410 E 6th St'},
        {location: 'east', name: 'The Brixton', address: '1412 E 6th St'},
        {location: 'east', name: 'Rhino Room', address: '1012 E 6th St'},
        {location: 'east', name: 'La Perla Bar', address: '1512 E 6th St'},
        {location: 'east', name: 'Grackle', address: '1700 E 6th St'},
        {location: 'east', name: 'La Holly', address: '2500 E 6th St'},
        {location: 'east', name: 'Attabar', address: '1300 E 6th St'},
        {location: 'east', name: 'Cuvee Coffee Bar', address: '2000 E 6th St'},
        {location: 'east', name: 'The Volstead lounge', address: '1500 E 6th St'},
        {location: 'east', name: 'Mezcaleria Tobala', address: '1816 E 6th St'},
        {location: 'east', name: 'The Liberty', address: '1618 E 6th St'},
        {location: 'east', name: 'Ah Sing Den', address: '1100 E 6th St'},
        {location: 'east', name: 'Milonga Room', address: '1201 E 6th St'},
        {location: 'east', name: 'Hi Hat Public House', address: '2121 E 6th St'},
        {location: 'east', name: 'The Eastern', address: '1511 E 6th St'},
        {location: 'east', name: 'Lazarus Brewing Co.', address: '1902 E 6th St'},
        {location: 'east', name: 'Hotel Vegas', address: '1502 E 6th St'},
        {location: 'east', name: 'Licha’s Cantina', address: '1306 E 6th St'},
        {location: 'east', name: 'Latchkey', address: '1308 E 6th St'},
        {location: 'east', name: 'Gelatria Gemelli', address: '1009 E 6th St'},
        {location: 'east', name: 'Yellow Jacket Social Club', address: '1704 E 5th St'},
        {location: 'east', name: 'The Hightower', address: '1209 E 7th St'},
        {location: 'fourth', name: 'Pêche', address: '208 W 4th St'},
        {location: 'fourth', name: 'Rain', address: '217 W 4th St'},
        {location: 'fourth', name: 'Halcyon', address: '218 W 4th St'},
        {location: 'fourth', name: 'Oilcan Harry’s', address: '211 W 4th S'},
        {location: 'fourth', name: 'Academia', address: '208 W 4th St'},
        {location: 'fourth', name: 'Hanger Lounge', address: '404 Colorado St'},
        {location: 'fourth', name: 'The Capital Grille', address: '117 W 4th St'},
        {location: 'fourth', name: 'RA Sushi Bar Restaurant', address: '117 W 4th St'},
        {location: 'fourth', name: 'Sellers Underground', address: '213 W 4th St'},
        {location: 'fourth', name: 'Highland Lounge', address: '404 Colorado St'}
      ]);
    })
};